import type { Metadata } from "next";
import { JetBrains_Mono, Inter } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
  weight: '400',
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: '400',
});

export const metadata: Metadata = {
  title: "La Casa Del Golf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        className={`${jetbrainsMono.variable} ${inter.variable} h-full antialiased font-inter`}
      >
        <body className="min-h-full flex flex-col">
          <ClerkProvider>
            <Navbar />
            {children}
          </ClerkProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
